spring.application.name=CorporateSocialMediaApp_BackEnd

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/socialmediaDB?useSSL=true&allowPublicKeyRetrieval=true&requireSSL=true&serverTimezone=Africa/Casablanca}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Lance}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
#CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
#CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
jwt.secret=5b0e78dbc5323e317fb019c4ef4c110c7705ce46dd8c73563147bad67536513b1b5e39917f776b83394098cbbec7f510b3ecea5c7708ace930c6c11bf1c04e7f
jwt.expiration-ms=3600000

spring.profiles.active=local
