package org.one.corporatesocialmediaapp_backend.Enums;

public enum ErrorCodes {
    // General
    INVALID_REQUEST,
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    OPERATION_NOT_ALLOWED,
    INTERNAL_SERVER_ERROR,

    // Auth
    AUTH_INVALID_CREDENTIALS,
    AUTH_UNAUTHORIZED,
    AUTH_FORBIDDEN,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,

    // User
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    USER_EMAIL_ALREADY_EXISTS,
    USER_USERNAME_ALREADY_EXISTS,

    // Post
    POST_NOT_FOUND,
    POST_CONTENT_EMPTY,
    POST_UPDATE_NOT_ALLOWED,
    POST_DELETE_NOT_ALLOWED,

    // Comment
    COMMENT_NOT_FOUND,
    COMMENT_CONTENT_EMPTY,
    COMMENT_DELETE_NOT_ALLOWED,

    // Interaction
    LIKE_ALREADY_EXISTS,
    LIKE_NOT_FOUND,
    FOLLOW_ALREADY_EXISTS,
    FOLLOW_SELF_NOT_ALLOWED
}
